### ISSUE TITLE
Problem with modsecurity in version nginx-more-1.16.1-4.el7.x86_64

### ISSUE THREAD

**Issue by eduardpalomo** [karljohns0n/nginx-more#10]
Hello Karl, I congratulate you for your excellent work, I have been using your compilations for more than 3 years with excellent results, I started testing modsecurity through the testing branch and everything was going well until today to update the latest version, at which time nginx It gave me an error and does not recognize the syntheses that refer to modsecurity.
nginx: [emerg] unknown directive "modsecurity" in

greeting

**Comment by karljohns0n** [comment]
Hi, thanks for the feedbacks! While nginx-more version with ModSecurity (1.16.1-3) was still in testing repo, I took the opportunity to change it for a dynamic module in 1.16.1-4. You can now install it using:

```
yum install --enablerepo=aeris-testing nginx-more-module-modsecurity 
``` 

More information in the [user guide](https://github.com/karljohns0n/nginx-more/blob/master/USER-GUIDE.md). I should push this version stable in few days. Please provide feedbacks.

**Comment by eduardpalomo** [comment]
Thank you very much Karl, I'm going to try and tell you how it went, regards

**Comment by karljohns0n** [comment]
Module ModSecurity is successfully passing CI tests for CentOS 7 and 8, see Travis [job](https://travis-ci.org/github/karljohns0n/pkg-aeris-release/jobs/664580948#L609). I've pushed nginx-more 1.16.1-4 stable.
