### ISSUE TITLE
Attempted to install on Centos 7

### ISSUE THREAD

**Issue by JamesShaver** [karljohns0n/nginx-more#11]
# yum install nginx-more
Resolving Dependencies
--> Running transaction check
---> Package nginx-more.x86_64 0:1.16.1-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================
 Package                                   Arch                                  Version                                     Repository                            Size
========================================================================================================================================================================
Installing:
 nginx-more                                x86_64                                1.16.1-4.el7                                aeris                                6.0 M

Transaction Summary
========================================================================================================================================================================
Install  1 Package

Total size: 6.0 M
Installed size: 17 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file /etc/logrotate.d/nginx from install of nginx-more-1.16.1-4.el7.x86_64 conflicts with file from package nginx-1:1.17.10-1.el7.ngx.x86_64
  file /usr/sbin/nginx from install of nginx-more-1.16.1-4.el7.x86_64 conflicts with file from package nginx-1:1.17.10-1.el7.ngx.x86_64
  file /var/log/nginx from install of nginx-more-1.16.1-4.el7.x86_64 conflicts with file from package nginx-1:1.17.10-1.el7.ngx.x86_64
  file /etc/nginx/nginx.conf from install of nginx-more-1.16.1-4.el7.x86_64 conflicts with file from package nginx-1:1.17.10-1.el7.ngx.x86_64
  file /usr/share/man/man8/nginx.8.gz from install of nginx-more-1.16.1-4.el7.x86_64 conflicts with file from package nginx-1:1.17.10-1.el7.ngx.x86_64

Error Summary
-------------

**Comment by karljohns0n** [comment]
Hello,

```
nginx-more-1.16.1-4.el7.x86_64 conflicts with file from package nginx-1:1.17.10-1.el7.ngx.x86_64
```

It seems you already have nginx 1.17.10 installed. Please choose between nginx-more and nginx. See README:

> Note that you cannot install nginx-more if nginx package is already installed on your system because both packages provide nginx binary and configurations. You need to choose between nginx-more OR nginx from CentOS / EPEL / Nginx repository. Nginx-more is compiled using a more recent GCC version than the others and it provides lots of ready-to-go WordPress / Laravel configurations. If nginx is already installed, it's possible to swap from nginx to nginx-more with a simple yum command, although be careful with your inplace configurations.

Karl

**Comment by JamesShaver** [comment]
Thanks Karl, I misunderstood the purpose as an addition, not a replacement.
