### ISSUE TITLE
Nginx 1.18

### ISSUE THREAD

**Issue by umair33** [karljohns0n/nginx-more#13]
Hi when is the build for nginx 1.18 coming ?

**Comment by karljohns0n** [comment]
Hi, I pushed them to the testing repo:

```
[root@team ~]# yum -q --enablerepo=aeris-testing list available nginx-more*
Available Packages
nginx-more.x86_64                                                   1.18.0-1.el7                                aeris-testing
nginx-more-module-modsecurity.x86_64                                1.18.0-1.el7                                aeris-testing
[root@team ~]# 
```

**Comment by umair33** [comment]
Thanks you for the quick reply one more thing I would like to ask will you be adding the quic patch from cloudflare.

**Comment by karljohns0n** [comment]
HTTP/3 isn't supported by OpenSSL yet, we have to wait until version 3.0 or 3.1. Cloudflare QUIC patch requires BoringSSL while default nginx and nginx-more are using OpenSSL.
