### ISSUE TITLE
Reverse Proxying Apache - PageSpeed - Question

### ISSUE THREAD

**Issue by Admiral-Noisy-Bottom** [karljohns0n/nginx-more#14]
This isn't an issue as such but more a question.

I've been using Nginx-More for six months with PageSpeed disabled. Nginx is caching an Apache http server and has been working fine.

Last week I decided to enable PageSpeed to see if I could squeeze a bit more performance out of it and found that the opposite happened. My sites appeared to perform slower.

My question is, when Nginx is configured as a Reverse Proxy Cache and PageSpeed is enabled am I effectively Caching the Cache?

PageSpeed has it's own Caching parameters so I have assumed it is a cache.

I have disabled PageSpeed again and the performance has improved.

I don't care if PageSpeed is enabled but am curious if I was caching a cache which is pointless.

**Comment by karljohns0n** [comment]
Proxy cache will decrease the TTFB while PageSpeed will decrease the time to load assets depending on which filters you enable (combine css/js, converting images to webp, etc.). When you enabled PageSpeed, did you refresh your proxy cache?

I don't have any reverse proxy with PageSpeed enabled anymore so I can't confirm the performance right now. It used to help.

**Comment by Admiral-Noisy-Bottom** [comment]
Thanks for your reply.

I did clear the cache after enabling PageSpeed. My Nginx Cache is in RAM all the time and I regularly run a pre-loading script. I'm not bothered if it gets lost on reboot because it is pre-loaded with all 6 sites.

Both Apache and Nginx are on Centos boxes (separate machines). Apache never runs more than 40% memory usage and Nginx uses only 10-15%.

My question about PageSpeed isn't terribly important and I was more curious than anything else. But I am glad you cleared it up for me regarding the css/js and use of webp. My images were delivered as webp already.

Thanks again.
