### ISSUE TITLE
CentOS Stream

### ISSUE THREAD

**Issue by yooneskh** [karljohns0n/nginx-more#19]
Thanks for your great work!

How will this project work with CentOS Stream?

**Comment by karljohns0n** [comment]
Hi, it should be simple to enable CentOS Stream support as long as a docker image is available to test it once built. I will take a look at this during the holidays.

**Comment by yooneskh** [comment]
Thanks for your reply @karljohns0n .
I searched around a little. there seems to be no major (or minor) docker image available for CentOS Stream 8. But there is a rather straight forward way of transforming a CentOS 8 image to CentOS Stream 8 image explained here [CentOS Stream](https://www.centos.org/centos-stream/)

**Comment by karljohns0n** [comment]
Hello,

I'm sorry but I wont support CentOS Stream. However, nginx-more now fully supports Rocky Linux 8 and AlmaLinux 8, see b8c9359e682cb6ce762d8b71d4bbe871becd97ff, and I can't wait to support EL9 when released as it's currently in beta!

Thanks!
