### ISSUE TITLE
How compile an rpm myself?

### ISSUE THREAD

**Issue by butsjoh** [karljohns0n/nginx-more#2]
Hi,

We would like to use your nginx-more as a base for adding additional modules as well. How would we be able todo that? Could you explain a bit how you build your packages? Maybe i can help in building a script that would run for example in a docker container and results in building an rpm. Glad to help out.

**Comment by butsjoh** [comment]
I think i already figured it out :) I just need to modify your spec file and then run an rpmbuild it seems (https://access.redhat.com/sites/default/files/attachments/rpm_building_howto.pdf)

I am not familiar with building rpm's but i will try it this way :)

**Comment by karljohns0n** [comment]
Hi,

I would highly recommend using mock to build this package for el6 and el7. You can install mock from EPEL on a CentOS 7 server. Clone this repo, get all modules sources with the right name, use mock to build both SRPMS and RPMS. You can always use the RPMS I provide with your own configurations. Updating the package wont overwrite your .conf files.

Good luck! :)

**Comment by karljohns0n** [comment]
Quick note before I close this issue. If you build this RPM with mock, you need to add Aeris repository in your mock configuration because the package depends on libraries outside CentOS base such as libmaxminddb-devel for GeoIP2.

File: /etc/mock/epel-7-x86_64.cfg
```
[aeris]
name=Aeris Packages for Enterprise Linux 7 - stable - $basearch
baseurl=http://repo.aerisnetwork.com/stable/centos/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AERIS
```

**Comment by butsjoh** [comment]
For reference to other people. I managed todo it with just these lines of code:

```
# Downloads all sources with http url listed in the .spec file
spectool -g -R SPECS/nginx-tp.spec

# Download deps listed in the .spec file
yum-builddep -y SPECS/nginx-tp.spec

# Starts build
rpmbuild -ba SPECS/nginx-tp.spec
```
