### ISSUE TITLE
My issue when installed on CentOS 7

### ISSUE THREAD

**Issue by cd-blank** [karljohns0n/nginx-more#20]
This is my story...

I have 2 VPS ready with the latest updates Centos 7.
`sudo yum -y upgrade`
`No packages marked for update`

**On Server 1**
1. I added some repos, such as: epel, remi, etc.
2. For nginx, I added codeit repo.
3. Upgraded Centos packages, and there are several packages updated.
4. I installed Nginx, configure nginx for testing.
I create a configuration file nginx in `/etc/nginx/conf.d/testing.conf`.
Test the config file:
`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok`
`nginx: configuration file /etc/nginx/nginx.conf test is successful`
and start nginx service, open a browser, and the website is running.
Then I plan to use aeris repo for nginx, replacing nginx codeit with nginx-more.
5. Remove existing nginx. `sudo yum -y remove nginx`.
6. Added aeris repo, then `sudo yum -y upgrade` and install nginx-more: `sudo yum -y install nginx-more`.
7. I modify the config file nginx: moving my config file from `/etc/nginx/conf.d/testing.conf` to `/etc/nginx/conf.d/vhosts/testing.conf`.
8. Test the config file:
`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok`
`nginx: configuration file /etc/nginx/nginx.conf test is successful`
restart nginx service, try it in browser and the website is running.

**On Server 2**
_"This is where the problem appears"._
I skipped some steps for this server, because I want to use aeris repo.
1. I added some repos, such as: epel, remi, etc.
2. Upgraded Centos packages, and there are several packages updated.
3. Added aeris repo, then `sudo yum -y upgrade` and install nginx-more: `sudo yum -y install nginx-more`.
4. I create a configuration file nginx in `/etc/nginx/conf.d/vhosts/testing.conf`.
5. Test the config file:
`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok`
`nginx: configuration file /etc/nginx/nginx.conf test is successful`
but I can't start nginx service and even I tried restarting the server, but that didn't help.
And there is no log information about the nginx service which is an error, I think.

"_This is the error.log_"
`2020/12/17 11:07:07 [info] 11095#11095: [ngx_pagespeed 1.13.35.2-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2020/12/17 11:07:07 [info] 11095#11095: pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:49
2020/12/17 11:32:34 [info] 11316#11316: [ngx_pagespeed 1.13.35.2-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2020/12/17 11:32:34 [info] 11316#11316: pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:49
2020/12/17 11:32:36 [info] 11319#11319: [ngx_pagespeed 1.13.35.2-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2020/12/17 11:32:36 [info] 11319#11319: pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:49
2020/12/17 11:32:43 [notice] 1050#1050: signal 15 (SIGTERM) received from 11330, exiting
2020/12/17 11:32:43 [notice] 1060#1060: exiting
2020/12/17 11:32:43 [notice] 1051#1051: exiting
2020/12/17 11:32:43 [notice] 1056#1056: exiting
2020/12/17 11:32:43 [notice] 1057#1057: exiting
2020/12/17 11:32:43 [notice] 1052#1052: exiting
2020/12/17 11:32:43 [notice] 1059#1059: exiting
2020/12/17 11:32:43 [notice] 1058#1058: exiting
2020/12/17 11:32:43 [notice] 1055#1055: exiting
2020/12/17 11:32:43 [notice] 1053#1053: exiting
2020/12/17 11:32:43 [notice] 1053#1053: exit
2020/12/17 11:32:43 [notice] 1058#1058: exit
2020/12/17 11:32:43 [notice] 1055#1055: exit
2020/12/17 11:32:43 [notice] 1052#1052: exit
2020/12/17 11:32:43 [notice] 1056#1056: exit
2020/12/17 11:32:43 [notice] 1059#1059: exit
2020/12/17 11:32:43 [notice] 1051#1051: exit
2020/12/17 11:32:43 [notice] 1057#1057: exit
2020/12/17 11:32:43 [notice] 1050#1050: signal 17 (SIGCHLD) received from 1055
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1055 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: signal 29 (SIGIO) received
2020/12/17 11:32:43 [notice] 1050#1050: signal 17 (SIGCHLD) received from 1060
2020/12/17 11:32:43 [notice] 1050#1050: cache manager process 1060 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: signal 29 (SIGIO) received
2020/12/17 11:32:43 [notice] 1050#1050: signal 17 (SIGCHLD) received from 1058
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1052 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1053 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1056 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1057 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1058 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: worker process 1059 exited with code 0
2020/12/17 11:32:43 [notice] 1050#1050: signal 29 (SIGIO) received`

So I executed the steps I skipped on Server 1.
I added codeit repo.
Upgraded Centos packages, and there are several packages updated.
Reinstall nginx-more, without changing nginx config file.
Then I start nginx service and now nginx service is running as well as the website.

**Comment by karljohns0n** [comment]
Hi,

I don't know `codeit` repository but it may conflict with `aeris` repository if they both have same packages with different version. Do you really need this repository? As for your error.log, I only see notice, no error. It might be related to SELinux enabled? You can read more about this [here](https://github.com/karljohns0n/nginx-more#selinux).

**Comment by cd-blank** [comment]
I don't know.
As I said before, it really happened.

Yes, maybe I did something wrong. here I just tell you what I experienced when installing.

For additional information:

1. I'm sure that as far as I can remember, I only installed one nginx (nginx-more) on both servers.
2. Both servers are fresh install.
3. Selinux status is enabled for both servers.
4. For Server 2, I didn't add codeit repo before (unlike what I did on server 1), but I couldn't start nginx service (so nginx status was inactive), but the vhost configuration file was OK and no error log, and I don't think there will be a conflict with the codeit repo, because I haven't added it yet.

So this is why I added codeit repo like on server 1.
After I added codeit repo, without changing any config, I can start nginx service.

Anyway, thank you for your superb work.

**Comment by karljohns0n** [comment]
The only thing I could think of is codit disabling SELinux or adding SELinux policy to allow nginx to start, that's why it worked. You could try again with a fresh server, install nginx-more without codit, disable SELinux or run `semanage permissive -a httpd_t`, it should works.
