### ISSUE TITLE
Nginx-more on Debian 10 - Not an issue, more of a question.

### ISSUE THREAD

**Issue by AdmiralNoisyBottom** [karljohns0n/nginx-more#22]
I've been using nginx-more for about 12 months on Centos 7 without any difficulty.

Given that most support for Centos has been dropped, or will be soon, I'm moving this box to a Debian based server.

I'm not an expert in Linux :( 

Can this be installed on a Debian distro with reasonable ease?

Thanks.

**Comment by karljohns0n** [comment]
Hi,

CentOS 7 will be EOL in 3 years and AlmaLinux/RockyLinux 8 (CentOS 8 replacement) will be EOL in 2029, therefore you will be able to use nginx-more for a long time ;)

As for your Debian question, nginx-more is only available for RHEL clone. Debian/Ubuntu require another packaging system and I don't have enough time to rebuild them unfortunately.

Karl

**Comment by AdmiralNoisyBottom** [comment]
Thanks Karl,

I understand your time constrains, have a few of my own. 

I'm still going to migrate a few machines to Debian inline with some of my other services. I guess I'll go back to standard nginx and add geoip2.

Thanks for all your work so far. You example configs have taught me a lot.

Thanks agian.

**Comment by karljohns0n** [comment]
Glad it was useful for you!
