### ISSUE TITLE
Rocky Linux

### ISSUE THREAD

**Issue by maszd** [karljohns0n/nginx-more#25]
Hi,

Any plan this great repo to support rocky linux?

Regards.

**Comment by karljohns0n** [comment]
Yes, I plan to support both rocky/alma, although the current centos8 repo should works just fine at the moment.

**Comment by karljohns0n** [comment]
Hello,

nginx-more now fully supports Rocky Linux 8 and AlmaLinux 8, see b8c9359e682cb6ce762d8b71d4bbe871becd97ff.

Thanks!
