### ISSUE TITLE
Bump to Nginx 1.21.4

### ISSUE THREAD

**Issue by sabishiii** [karljohns0n/nginx-more#27]
Hi, Nginx v1.21.4 just came out today, would it be possible to create a new nginx-more build? Here's the changelog for the latest Nginx release: https://forum.nginx.org/read.php?2,292739

In any case, thanks a lot for maintaining this package!

**Comment by karljohns0n** [comment]
Hi, nginx-more uses stable branch of nginx, so the next version will be 1.22.0. Thanks for using this package ;)

Karl
