### ISSUE TITLE
Possibility to include modsecurity?

### ISSUE THREAD

**Issue by washek** [karljohns0n/nginx-more#3]
Hi, thank you for your great work. Nginx-more saved me a lot of troubles :-)

I was thinking that it would be cool to add modsecurity module: https://github.com/SpiderLabs/ModSecurity-nginx

Thank you for your time!
Washek

**Comment by karljohns0n** [comment]
Hi Washek,

Thanks for the feedbacks. It's already planned to add ModSecurity 3 Nginx Connector as I was supporting ModSecurity 2 before but first I need to build libmodsecurity because the new connector depends on this lib. I will take a look at this in the next weeks but no real ETA. 

I'll update on ModSecurity 3 nginx connector status in this issue. 

Karl

**Comment by washek** [comment]
Thank you for your quick response. I will look forward to this.

Btw. do you accept donations? I did not find your paypal account or something similar.

**Comment by karljohns0n** [comment]
I'm not looking for donations, just spread the word if you like this package :)

**Comment by karljohns0n** [comment]
Quick update, I've been able to build libmodsecurity for el7 however it's a bit tricky on el6. It requires a recent GCC version and both lua / yajl packages are pretty old. I will see if I only build modsecurity v3 for el7 or also el6.

**Comment by washek** [comment]
Thank you for the update. Since el6 will have EOL next year, IMHO it's not worth the extra effort.

**Comment by karljohns0n** [comment]
That's also what I think. I will build test rpm this week so you can test.

**Comment by karljohns0n** [comment]
I did some quick tests with basic rules, it seems to work well. 

Here's the command if you want to test the rpm. It's currently outside the repo so you need the full URL and libmodsecurity is in testing repo hence you need to enable it.
```
yum --enablerepo=aeris-testing update https://repo.aerisnetwork.com/archive/nginx-more-1.14.2-4.el7.x86_64.rpm
```

Nginx output:
```
[root@dev ~]# nginx -V
nginx version: nginx/1.14.2
custom build maintained on github.com/karljohns0n/nginx-more
built by gcc 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
built with OpenSSL 1.1.1b  26 Feb 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/cache/client_body --http-proxy-temp-path=/var/lib/nginx/cache/proxy --http-fastcgi-temp-path=/var/lib/nginx/cache/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/cache/uwsgi --http-scgi-temp-path=/var/lib/nginx/cache/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --user=nginx --group=nginx --with-compat --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_image_filter_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_geoip_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-threads --with-stream --with-stream_ssl_module --with-stream_realip_module --with-http_slice_module --with-stream_ssl_preread_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DTCP_FASTOPEN=23' --with-cc=/opt/rh/devtoolset-7/root/usr/bin/gcc --with-openssl=modules/openssl-1.1.1b --add-module=modules/ngx_modsecurity_nginx-1.0.0 --add-module=modules/ngx_headers_more-0.33 --add-module=modules/ngx_cache_purge-2.3 --add-module=modules/ngx_module_vts-0.1.18 --add-module=modules/ngx_pagespeed-1.13.35.2-stable --add-module=modules/ngx_brotli-snap20190307 --add-module=modules/ngx_http_geoip2_module-3.2 --add-module=modules/ngx_echo-0.61
```

**Comment by dvershinin** [comment]
@washek [nginx extras](https://www.getpagespeed.com/server-setup/nginx/install-modsecurity-nginx-module-on-centos-7) got you covered.

**Comment by karljohns0n** [comment]
@dvershinin Please stop spamming all my blog post and GitHub. Thanks.

**Comment by karljohns0n** [comment]
Hi Marc,

Thanks for using nginx-more! I built a package with modsec a few months ago, see [comment](https://github.com/karljohns0n/nginx-more/issues/3#issuecomment-479076549), however I didn't have any feedbacks so it's not pushed on stable yet. Can you test this package on a dev server and provide feedbacks?

**Comment by marcgenou** [comment]
To my very limited knowledge in this matter, seems to be working fine:

2019/10/12 14:08:02 [warn] 12843#12843: *152 [client x.x.x.x] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `10' ) [file "/usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "79"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/aphpfilethatdonotexist.php"] [unique_id "157088208252.963400"] [ref ""], client: x.x.x.x, server: XXXX, request: "GET /aphpfilethatdonotexist.php?something=../../etc HTTP/1.1", host: "XXXX"
2019/10/12 14:08:47 [warn] 12843#12843: *155 [client x.x.x.x] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "79"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/foo"] [unique_id "157088212769.761584"] [ref ""], client: x.x.x.x, server: XXXX, request: "GET /foo?username=1'%20or%20'1'%20=%20' HTTP/1.1", host: "XXXX"
2019/10/12 14:09:27 [warn] 12842#12842: *157 [client x.x.x.x] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `15' ) [file "/usr/local/owasp-modsecurity-crs-3.2.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "79"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/"] [unique_id "157088216761.970794"] [ref ""], client: x.x.x.x, server: XXXX, request: "GET /?q="><script>alert(1)</script> HTTP/1.1", host: "XXXX"

**Comment by karljohns0n** [comment]
Great, let me do a new build with ModSecurity based on the latest release. I'll get back to you shortly.

**Comment by derevandal** [comment]
@karljohns0n any progress in this issue?

**Comment by karljohns0n** [comment]
2 years later, they finally released modsecurity nginx connector v1.0.1. I feel more confident to integrate it now. I'll have a test build in the next few days.

**Comment by karljohns0n** [comment]
I've pushed nginx-more 1.16.1-3 to testing with ModSecurity nginx connector:

```
[root@dev ~]# nginx -V
nginx version: nginx/1.16.1
custom build maintained on github.com/karljohns0n/nginx-more
built by gcc 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/cache/client_body --http-proxy-temp-path=/var/lib/nginx/cache/proxy --http-fastcgi-temp-path=/var/lib/nginx/cache/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/cache/uwsgi --http-scgi-temp-path=/var/lib/nginx/cache/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --user=nginx --group=nginx --with-compat --with-file-aio --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_image_filter_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_geoip_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-threads --with-stream --with-stream_ssl_module --with-stream_realip_module --with-http_slice_module --with-stream_ssl_preread_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DTCP_FASTOPEN=23' --with-cc=/opt/rh/devtoolset-7/root/usr/bin/gcc --with-openssl=modules/openssl-1.1.1d --with-http_v2_hpack_enc --add-module=modules/ngx_modsecurity-1.0.1 --add-module=modules/ngx_headers_more-0.33 --add-module=modules/ngx_cache_purge-2.3 --add-module=modules/ngx_module_vts-0.1.18 --add-module=modules/ngx_pagespeed-1.13.35.2-stable --add-module=modules/ngx_brotli-snap20191118 --add-module=modules/ngx_http_geoip2_module-3.3 --add-module=modules/ngx_echo-0.61
```

```
[root@dev ~]# grep -i modsec /var/log/nginx/error.log
2020/01/03 01:02:22 [notice] 30916#30916: ModSecurity-nginx v1.0.1 (rules loaded inline/local/remote: 0/0/0)
2020/01/03 01:02:22 [notice] 30919#30919: ModSecurity-nginx v1.0.1 (rules loaded inline/local/remote: 0/0/0)
```

Can you guys test and provide feedbacks?

```
yum --enablerepo=aeris-testing install nginx-more
```

**Comment by karljohns0n** [comment]
Hello,

ModSecurity is now available as dynamic module in testing repo for CentOS 7 / 8 and will be pushed stable in few days:

```
dnf install nginx-more-module-modsecurity --enablerepo=aeris-testing
```

See [User Guide](https://github.com/karljohns0n/nginx-more/blob/master/USER-GUIDE.md).

**Comment by sthasanto** [comment]
I had installed nginx-more on centos 7 server but when I add "modsecurity on;" in nginx.conf file,I get nginx: [emerg] unknown directive "modsecurity" error.

[root@cis nginx]# nginx -V
nginx version: nginx/1.18.0
custom build maintained on github.com/karljohns0n/nginx-more
built by gcc 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 
built with OpenSSL 1.1.1i  8 Dec 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/cache/client_body --http-proxy-temp-path=/var/lib/nginx/cache/proxy --http-fastcgi-temp-path=/var/lib/nginx/cache/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/cache/uwsgi --http-scgi-temp-path=/var/lib/nginx/cache/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --user=nginx --group=nginx --with-compat --with-file-aio --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_image_filter_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_geoip_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-threads --with-stream --with-stream_ssl_module --with-stream_realip_module --with-http_slice_module --with-stream_ssl_preread_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DTCP_FASTOPEN=23' --with-cc=/opt/rh/devtoolset-8/root/usr/bin/gcc --with-openssl=modules/openssl-1.1.1i --with-http_v2_hpack_enc --add-dynamic-module=modules/ngx_modsecurity-1.0.1 --add-module=modules/ngx_headers_more-0.33 --add-module=modules/ngx_cache_purge-2.3 --add-module=modules/ngx_module_vts-0.1.18 --add-module=modules/ngx_pagespeed-1.13.35.2-stable --add-module=modules/ngx_brotli-snap20201209 --add-module=modules/ngx_http_geoip2_module-3.3 --add-module=modules/ngx_echo-0.61

Please guide me.

**Comment by karljohns0n** [comment]
Hello,

> Please guide me to configure modecurity with nginx-more.

You only need to install nginx-more-module-modsecurity. I just tested it without issue using a CentOS 7 docker image:

```bash
[root@770dae05a6a5 ~]# yum install nginx-more nginx-more-module-modsecurity -y -q
[root@770dae05a6a5 ~]# systemctl start nginx
[root@770dae05a6a5 ~]# grep -i modsec /var/log/nginx/error.log 
2021/03/11 14:27:25 [notice] 189#189: ModSecurity-nginx v1.0.1 (rules loaded inline/local/remote: 0/0/0)
2021/03/11 14:27:31 [notice] 194#194: ModSecurity-nginx v1.0.1 (rules loaded inline/local/remote: 0/0/0)
[root@770dae05a6a5 ~]#
```

**Comment by sthasanto** [comment]
Thank you for the guide. I had clean installed nginx-more on a fresh centos
7 and issue is solved. But unable to fix issue on preinstalled nginx-more.
