### ISSUE TITLE
el9 support

### ISSUE THREAD

**Issue by karljohns0n** [karljohns0n/nginx-more#32]
I started working on el9 support for nginx-more. There's only issues so far with two modules: [PageSpeed](https://github.com/apache/incubator-pagespeed-ngx/issues/1743) and [VTS](https://github.com/vozlt/nginx-module-vts/issues/232).

I will keep this issue for tracking el9 release.

**Comment by skrlance** [comment]
I will update you if I find any bug. Thanks and it means a lot to us!!

**Comment by skrlance** [comment]
For modules like PageSpeed and VTS that hasn't been updated from years, please compile one without them so we can use nginx-more on El9 for now! After the issues get fixed, then please compile new one including them!!
Besides, for me VTS and PageSpeed work can be performed using analytics and WP plugin until they are available!!
Thanks

**Comment by oncena** [comment]
Hi Karl. I would really appreciate it if you just happen to be able to release a working version for EL9 without all the bells and whistles that currently have issues. Thank you.

**Comment by aabiskar1** [comment]
I also agree Karl, please compile one with those thats working. Let's not stop because of Pagespeed and VTS. We are already on El9 and waiting to install nginx-more for it. You can compile including those after the issues gets fixed.

**Comment by skrlance** [comment]
Update: I have successfully build the rpm file of nginx-more 1.22.0 for EL9 without pagespeed and VTS. However, I wasn't able to compile rpm file of nginx-more-module-modsecurity because spec file is not present here. Can you help Karl?
As for more info, nothing has been changed in the compiled file. It is just normal nginx-more build by Karl Johnson as there is.

**Comment by karljohns0n** [comment]
A new version of VTS has been released today. I will create el9 builds this week and update this issue.

**Comment by skrlance** [comment]
I just checked, latest dev version has fixed the VTS issue when compiling.

**Comment by karljohns0n** [comment]
Yes I did a build yesterday, it went fine. Only missing PageSpeed. I'll probably skip this module for el9, at least to start.

**Comment by karljohns0n** [comment]
I pushed el9 build stable including latest module VTS 0.2.1 but still without PageSpeed (for now).

Package aeris-release should be reinstalled as it uses a new key.

```bash
[root@81b6c7c5497f ~]# dnf clean all && dnf reinstall -y aeris-release 
[root@81b6c7c5497f ~]# dnf install nginx-more nginx-more-module-modsecurity
[root@81b6c7c5497f ~]# nginx -V
nginx version: nginx/1.22.0
custom build maintained on github.com/karljohns0n/nginx-more
built by gcc 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC) 
built with OpenSSL 3.0.5 5 Jul 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/cache/client_body --http-proxy-temp-path=/var/lib/nginx/cache/proxy --http-fastcgi-temp-path=/var/lib/nginx/cache/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/cache/uwsgi --http-scgi-temp-path=/var/lib/nginx/cache/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --user=nginx --group=nginx --with-compat --with-file-aio --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_image_filter_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-threads --with-stream --with-stream_ssl_module --with-stream_realip_module --with-http_slice_module --with-stream_ssl_preread_module --with-debug --with-cc-opt='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DTCP_FASTOPEN=23' --with-openssl=modules/openssl-3.0.5 --with-openssl-opt=enable-ktls --with-http_v2_hpack_enc --add-dynamic-module=modules/ngx_modsecurity-1.0.3 --add-module=modules/ngx_headers_more-0.34 --add-module=modules/ngx_cache_purge-2.3 --add-module=modules/ngx_module_vts-0.2.1 --add-module=modules/ngx_brotli-snap20220505 --add-module=modules/ngx_http_geoip2_module-3.4 --add-module=modules/ngx_echo-0.62
```

Please provide feedback. I only tested with Docker at the moment. Thanks!

**Comment by oncena** [comment]
Works like a charm on Rocky Linux 9. Thank you.

**Comment by skrlance** [comment]
The repos are working good and stable so this issue should be marked resolved!!
