### ISSUE TITLE
 nginx-more-1.22.1-1.el8.x86_64 breaks ngx_cache_purge

### ISSUE THREAD

**Issue by fe-os-rz** [karljohns0n/nginx-more#37]
Dear nginx-more maintainer,

with  nginx-more-1.22.1-1.el8.x86_64, ngx_cache_purge crashes:

```
[root@<redacted> ~]# curl -D- -X PURGE http://<redacted>.rz.uni-osnabrueck.de/proxy-cache-test/test.html
curl: (52) Empty reply from server
```

with  nginx-more-1.18.0-4.el8.x86_64   (last working version with ngx_cache_purge), everything is fine:

```
# curl -D- -X PURGE http://<redacted>.rz.uni-osnabrueck.de/proxy-cache-test/test.html
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 06 Dec 2022 14:15:00 GMT
Content-Type: text/html
Content-Length: 288
Connection: keep-alive

<html>
<head><title>Successful purge</title></head>
<body bgcolor="white">
<center><h1>Successful purge</h1>
<br>Key : /proxy-cache-test/test.html
<br>Path: /var/cache/nginx/proxy/4/56/db27baca3d683b4fa84088b4549c0564
</center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

This might be solved by:

https://github.com/FRiCKLE/ngx_cache_purge/pull/51/commits/c8ca321b909cb3d9371db4509f1064045d7e0b1c

Thanx in advance!
Frank

**Comment by karljohns0n** [comment]
Patch has been rolled in with e42c6b724d30ff1b84dfaaf3cd065749a54b1deb. It will be in next build. Thank you!

**Comment by karljohns0n** [comment]
Extended stats module? What's that? ;)

**Comment by fe-os-rz** [comment]
Oh, I used the wrong naming; I was thinking of: https://github.com/vozlt/nginx-module-vts
