### ISSUE TITLE
1.26.0 Update Required

### ISSUE THREAD

**Issue by skrlance** [karljohns0n/nginx-more#44]
Hi Karl, please update NGINX-more to v1.26.0 using latest version of modules and OpenSSL. We also need update on the sources.

Besides, I also read about freeNGINX but didn't understand much what it is up to? Which one we will be using freeNGINX or from nginx.org?

**Comment by karljohns0n** [comment]
Hi,

I'm a bit busy right now but it's in my plan. For now it will still be nginx based, we will see how it goes!

**Comment by karljohns0n** [comment]
Hello,

I created the `1.26` branch. It compiles just fine on el9, will try el8 and el7 shortly. The only issue right now is that HPACK is not compatible anymore.

https://github.com/kn007/patch?tab=readme-ov-file#nginxpatch-discontinued
