### ISSUE TITLE
CentOS 8

### ISSUE THREAD

**Issue by asucrews** [karljohns0n/nginx-more#7]
Just wondering what the plan for CentOS 8 is for this great project.

**Comment by karljohns0n** [comment]
CentOS 8 package is definitely on the roadmap, I should try some build soon using Docker. I'm waiting for [8.1](https://wiki.centos.org/About/Building_8.x) before getting my hands on CentOS 8. I will then check if all the package dependencies are met else I will build them.

**Comment by ivmm** [comment]
> CentOS 8 package is definitely on the roadmap, I should try some build soon using Docker. I'm waiting for [8.1](https://wiki.centos.org/About/Building_8.x) before getting my hands on CentOS 8. I will then check if all the package dependencies are met else I will build them.

You can use the developer version of RHEL8.1 for testing, and the developer version is free to use. https://developers.redhat.com/

**Comment by karljohns0n** [comment]
I've built nginx-more dependencies for CentOS 8 such as GeoIP and ModSecurity:

https://repo.aerisnetwork.com/testing/centos/8/x86_64/repoview/

I should be able to get a el8 test release soon.

**Comment by karljohns0n** [comment]
Packages for el8 have been released in testing repo and will be pushed stable in a couple of days.

```
dnf install -y https://repo.aerisnetwork.com/pub/aeris-release-8.rpm
dnf install nginx-more --enablerepo=aeris-testing
dnf install nginx-more-module-modsecurity --enablerepo=aeris-testing
```
