### ISSUE TITLE
modsecurity

### ISSUE THREAD

**Issue by asucrews** [karljohns0n/nginx-more#9]
Hello, it doesn't look the modsecuirty is being installed or enabled rpm install on Centos 7?  Unless i am missing something.

 yum install nginx-more
Package nginx-more-1.16.1-2.el7.x86_64 already installed and latest version
Nothing to do

nginx -t
nginx: [emerg] unknown directive "ModSecurityEnabled" in /etc/nginx/nginx.conf:187
nginx: configuration file /etc/nginx/nginx.conf test failed

2>&1 nginx -V | tr -- - '\n' | grep _module
http_ssl_module
http_realip_module
http_addition_module
http_image_filter_module
http_sub_module
http_dav_module
http_flv_module
http_mp4_module
http_gunzip_module
http_gzip_static_module
http_geoip_module
http_random_index_module
http_secure_link_module
http_degradation_module
http_stub_status_module
http_auth_request_module
http_xslt_module
http_v2_module
mail_ssl_module
stream_ssl_module
stream_realip_module
http_slice_module
stream_ssl_preread_module
module=modules/ngx_module_vts
module=modules/ngx_http_geoip2_module

**Comment by asucrews** [comment]
what is interesting is when i enable testing repo i get modsec.

**Comment by karljohns0n** [comment]
Hi, ModSecurity is only available in the testing repo for now. I will probably push it to stable the same time I release CentOS 8 package. I've been quite busy these past weeks but I should release it soon.

**Comment by karljohns0n** [comment]
Hello,

ModSecurity is now available as dynamic module in testing repo and will be pushed stable in few days:

```
dnf install nginx-more-module-modsecurity --enablerepo=aeris-testing
```

See [User Guide](https://github.com/karljohns0n/nginx-more/blob/master/USER-GUIDE.md).
